# -*- coding: utf-8 -*-
"""Calculadora_Version2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WAW1T2jbYbK42kQOU0kma_rY0NlOhUiT
"""

print("_ _ _ __Calculadora_ _ _ _ _")
num1 = int(input("Ingrese un numero: "))
num2 = int(input("Ingrese otro numero: "))
num3 = int(input("Ingrese otro numero: "))

while True:
  print("Menu de opciones")
  print("1.Sumar")
  print("2.Restar")
  print("3.Dividir")
  print("4.Multiplicar")
  opc = int(input("Ingrese una opcion: "))
  if opc == 1:
    print("La suma es: ", num1 + num2 + num3)
    break
  elif opc == 2:
    print("La resta es: ", num1 - num2 - num3)
    break
  elif opc == 3:
    print("La division es: ", num1 / num2 / num3)
    break
  elif opc == 4:
    print("La multiplicacion es: ", num1 * num2 * num3)
    break